# Generated by Django 4.1.3 on 2023-05-26 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0002_rename_category_id_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fundapp.register'),
        ),
    ]
